overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-io.yml
targets:
  - "docs/source/conf.py": "docs/conf.py_t"
  - setup.py: io_setup.py.jj2
  - .travis.yml: travis.yml.jj2
  - "tests/requirements.txt": "tests/custom-requirements.txt.jj2"
  - README.rst: io_readme.rst.jj2
  - "docs/source/index.rst": "docs/source/index.rst"
