configuration:
  configuration_dir: "git://github.com/pyexcel/pyexcel-mobans!/config"
  template_dir:
  - "git://github.com/moremoban/pypi-mobans.git?branch=dev&submodule=true!/templates"
  - "git://github.com/pyexcel/pyexcel-mobans.git!/templates"
  - ".moban.d"
  configuration: pyexcel-io.yml
targets:
  - "docs/source/conf.py": "docs/conf.py_t"
  - setup.py: io_setup.py.jj2
  - .travis.yml: travis.yml.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - LICENSE: NEW_BSD_LICENSE.jj2
  - test.sh: test.script.jj2
  - test.bat: test.script.jj2
  - README.rst: io_readme.rst.jj2
  - "docs/source/index.rst": "docs/source/index.rst"
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
  - lint.sh: lint.script.jj2
